-- Run this in your Supabase SQL Editor to create the tables

-- Assets Table
create table assets (
  id bigint generated by default as identity primary key,
  "serialNumber" text not null,
  model text not null,
  type text not null,
  status text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Staff Table
create table staff (
  id bigint generated by default as identity primary key,
  "employeeId" text not null,
  name text not null,
  department text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Assignments Table
create table assignments (
  id bigint generated by default as identity primary key,
  "assetId" bigint references assets(id),
  "staffId" bigint references staff(id),
  "issueDate" date not null,
  "returnDate" date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Repairs Table
create table repairs (
  id bigint generated by default as identity primary key,
  "assetId" bigint references assets(id),
  "faultDescription" text not null,
  "partsReplaced" text,
  cost numeric,
  date date not null,
  technician text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CCTV Table
create table cctv (
  id bigint generated by default as identity primary key,
  "cameraLocation" text not null,
  status text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
