-- Create Premises Table
CREATE TABLE IF NOT EXISTS premises (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed default premises if table is empty
INSERT INTO premises (name, sort_order)
SELECT name, sort_order FROM (VALUES 
  ('Main Premise', 0)
) AS t(name, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM premises);
