-- Create Floors Table
CREATE TABLE IF NOT EXISTS floors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed default floors if table is empty
INSERT INTO floors (name, sort_order)
SELECT name, sort_order FROM (VALUES 
  ('Basement', 0),
  ('Ground', 1),
  ('1st', 2),
  ('2nd', 3),
  ('3rd', 4),
  ('4th', 5),
  ('5th', 6),
  ('6th', 7),
  ('Rooftop', 8)
) AS t(name, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM floors);
