-- Update Assets table for detailed specs
ALTER TABLE assets ADD COLUMN IF NOT EXISTS "specs_ram" text;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS "specs_storage" text;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS "specs_processor" text;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS "specs_os" text;

-- Create Accessories Table
create table accessories (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g. "8GB DDR4 RAM", "USB Mouse"
  type text not null, -- "RAM", "Storage", "Peripheral", "Cable"
  quantity integer default 0,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Accessory Usage Log (to track history)
create table accessory_logs (
  id bigint generated by default as identity primary key,
  "accessoryId" bigint references accessories(id),
  "assetId" bigint references assets(id),
  "action" text not null, -- 'Installed', 'Removed'
  quantity_change integer not null, -- e.g. -1 for install, +1 for remove
  date date not null,
  technician text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
